name = "spark_ml_dsa"
version = "1.0.0"
description = "SPARK Ada ML-DSA-87 (FIPS 204, Dilithium) post-quantum digital signatures"
licenses = "Apache-2.0"
authors = ["AnubisQuantumCipher <sic.tau@pm.me>"]
maintainers = ["AnubisQuantumCipher <sic.tau@pm.me>"]
website = "https://github.com/AnubisQuantumCipher/spark_ml_dsa"
tags = ["post-quantum", "dilithium", "signatures", "spark", "fips-204"]
project-files = ["spark_ml_dsa.gpr"]

long-description = """
ML-DSA-87 post-quantum digital signatures (FIPS 204). Module-lattice based, Category 5 security.
"""
